### ISSUE TITLE
Component should set className in render based on this.props.active and not this.state.active.

### ISSUE THREAD

**Issue by invalidred** [arnthor3/react-bootstrap-toggle#1]
Hi,

Good job on your component. 

There is a small issue when I am using your component in my project. The problem is the component should always infer active value from props and not from state.

So it should not be
```
className={this.state.active ? activeClass : inactiveClass} 
```

Rather it should be 

```
className={this.props.active ? activeClass : inactiveClass} 
```

The reason is, we make API calls to get some object and the object's bool value should determine the active state. The objects bool valus is passed through this.props.

**Comment by arnthor3** [comment]
Hi, 

Thanks!

I forgot to put it in the readme but you can set the initial state with the active prop. I will update the readme later on today.
