### ISSUE TITLE
deprecations in react 15.5.0 

### ISSUE THREAD

**Issue by bigkrp** [arnthor3/react-bootstrap-toggle#13]
I have warning
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

It's about https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

It seams you use deprecated PropTypes
https://github.com/arnthor3/react-bootstrap-toggle/blob/master/src/react-bootstrap-toggle.jsx#L1

I have this error from dist/react-bootstrap-toggle.js:27
var eitherStringOrInteger = _react.PropTypes.oneOfType([_react.PropTypes.string, _react.PropTypes.number]);

**Comment by jeffvandyke** [comment]
Just noticed this same thing in my project too, it should be a pretty easy fix, let me know if you would like a pull-request or not.

**Comment by arnthor3** [comment]
A PR would be awesome thanks :)

**Comment by jeffvandyke** [comment]
Thanks! I don't suppose you would mind publishing the update to npm; perhaps a minor version tick is in order? I'm not certain on npm publishing procedures.

**Comment by arnthor3** [comment]
Sure, I will do it the first chance I get tonight, thanks for the fix.

**Comment by arnthor3** [comment]
Published
