### ISSUE TITLE
Disabled is not working

### ISSUE THREAD

**Issue by Karthi-SRV** [arnthor3/react-bootstrap-toggle#16]
`<Toggle
      on={<h5>Enabled</h5>}
      off={<h5>Disabled</h5>}
      size="xs"
      offstyle="danger"
      active={this.state.status}
      onClick={this.statusChangeSwitch.bind(this)}
      disabled
/>`

Disable the toggle is not working

**Comment by arnthor3** [comment]
can you switch the state with the disabled prop on?

**Comment by arnthor3** [comment]
In the latest version the disabled prop is working but however the disabled prop is just on the root component and it looks like it's not working. I am pushing a new fix for this. Thanks for the catch
