### ISSUE TITLE
Enzyme hangs when trying to mount a component with "ToggleButton" in it

### ISSUE THREAD

**Issue by TAGC** [arnthor3/react-bootstrap-toggle#17]
I found that one of my unit test suites caused my Jest test runner to hang indefinitely. I traced it down to trying to mount the component in the unit tests for that suite. I investigated further and found the issue was caused by using "ToggleButton" in the React component under test.

```js
<span>
    <ToggleButton onstyle='danger' height='34px' active={true}/>
</span>
```

Which is imported with:

```js
import ToggleButton from 'react-bootstrap-toggle';
```

**Environment**

 - Windows 7 64-bit
 - Electron 1.7.3 application
 - react-bootstrap-toggle@2.0.8
 - react@15.6.1
 - jest@20.0.4
 - enzyme@2.8.2

**Comment by arnthor3** [comment]
Could you try setting the width prop as well? The Toggle is trying to calculate the size of the component.

**Comment by TAGC** [comment]
Adding "width" allows the tests to run, yeah.
