### ISSUE TITLE
Allow to set width 100%

### ISSUE THREAD

**Issue by Grzesie2k** [arnthor3/react-bootstrap-toggle#22]

**Comment by arnthor3** [comment]
You can do that, just pass width="100%" and it will span to the width of the parent container. Could you check again?

**Comment by arnthor3** [comment]
You can throw in "100%". I noticed that it was still calculating the width even though the width prop was set. I fixed that, hopefully.. :)

**Comment by Grzesie2k** [comment]
Can You publish new version to npm registry?

**Comment by arnthor3** [comment]
Will do later today.
