### ISSUE TITLE
react v16

### ISSUE THREAD

**Issue by seriousManual** [arnthor3/react-bootstrap-toggle#24]
hello,
npm complains because react-bootstrap-toggle demands a 15.* version of react as a peer dependency.
as far as i can see it works fine with v16.2, could to update the peer dependency requirements in the package.json?

thx!

**Comment by arnthor3** [comment]
It's fixed thanks for the heads-up :)

**Comment by seriousManual** [comment]
thanks!

**Comment by danosaure** [comment]
Would be good if you accept both 15 and 16.
