### ISSUE TITLE
Remove dev files when publish

### ISSUE THREAD

**Issue by danosaure** [arnthor3/react-bootstrap-toggle#25]
Can you add all dev files in your `.npmignore` so when published, we are not stuck with files like `.babelrc` which impacts our building process?

It's probably should only contain the `dist/` folder and `package.json` and some `readme`, but nothing like `.??*` nor the `src/` folder.

Also, if your package is also compatible with react@15, would appreciate if the `peerDependencies` be adjusted so too. Right now, we are trying to use the `2.2.3` because it's for our project... or just publish a tag `react-15` would be appreciated.

Thanks,

**Comment by arnthor3** [comment]
Sure, if you are in a hurry you could do a pull request otherwise I will be able to tackle this later this week.

**Comment by danosaure** [comment]
Great, I think my colleague would make a PR to get this rolling.

**Comment by arnthor3** [comment]
Awesome thanks. 
Don´t we need to update the peer dependencies to include react v.15* ?

**Comment by danosaure** [comment]
Yeah, sorry, I was not familiar with that part, for which versions your plugin would be compatible, but maybe if you just set them as `>=15.0.0` when you bump the version?

```
  "peerDependencies": {
    "react": ">=15.0.0",
    "react-dom": ">=15.0.0"
  }
```

**Comment by arnthor3** [comment]
How about something like this from React-MD? 

```javascript
  "peerDependencies": {
    "react": ">= 15.3.0 || 16.0.0",
    "react-dom": ">= 15.3.0 || 16.0.0"
  },
```

And maybe expand it like this

```javascript
  "peerDependencies": {
    "react": ">= 15.0.0 || >= 16.0.0",
    "react-dom": ">= 15.0.0 || >= 16.0.0"
  },
```

Maybe something like this would work?

**Comment by danosaure** [comment]
Sounds good if that works. I admit that I have never do alternatives peerDependencies. Also, I usually don't have a space after the `>=`:

```
  "peerDependencies": {
    "react": ">=15.0.0 || >=16.0.0",
    "react-dom": ">=15.0.0 || >=16.0.0"
  },
```

I have tried with above settings and it complains when I don't install any react, or react@0. So it sounds good like this.

**Comment by arnthor3** [comment]
I will build and publish like this tonight, thanks for the help 👍

**Comment by danosaure** [comment]
play with `npm outdated` if you want too... Some versions are very old. But that can wait as it won't impact our work.

**Comment by arnthor3** [comment]
published, thanks for the help.

**Comment by danosaure** [comment]
Hey, I just looked at your peerDependency update, and notice you didn't push the version bump commit. Just in case you forgot to commit and push.
