### ISSUE TITLE
broken npm package

### ISSUE THREAD

**Issue by seriousManual** [arnthor3/react-bootstrap-toggle#27]
hi,
our CI picked up the latest version (2.2.6, published 14h ago) and it seems to be broken. thats the content of the downloaded package:
![image](https://user-images.githubusercontent.com/1330022/35968867-59e5a4a6-0cc5-11e8-96cf-82d28c90e718.png)

after switching to 2.2.5 it works again

**Comment by arnthor3** [comment]
Hi, we were cleaning things up last night. Could I get some error output from the CI to know where to look?

I suspect it might be the change in the peer dependencies

```javascript
  "peerDependencies": {
    "react": ">=15.0.0",
    "react-dom": ">=15.0.0"
  }
```

I swiped that line from another project that i use :)

I will take a look into this asap.

**Comment by arnthor3** [comment]
Hi, on the picture it seems that the dist folder got lost somehow? A bit strange because  I get it when I do a install of the package via npm.

**Comment by seriousManual** [comment]
i tried it again, the dist folder seems to be there now.
i dont know what the reason for this is, it happened on at least to seperate systems (CI and my machine).
