### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by Fatal1stZ** [arnthor3/react-bootstrap-toggle#30]
Does it suppot bootstrap 4?
Or any fast suggest how to port it ?

**Comment by arnthor3** [comment]
I have not tried it yet but it looks like it should work. The classnames are the same so it should work.

**Comment by Fatal1stZ** [comment]
I guess it misses some classes actually.
It looks pretty strange out of the box.

**Comment by Fatal1stZ** [comment]
Can you take a look at this? For example there is no btn-default in bootstrap 4.

**Comment by arnthor3** [comment]
Yeah, of course. I will look into this later on today.

**Comment by arnthor3** [comment]
You can for now add a class for the btn-default to get the handle back. You can just add to you css
```css
.btn-default { background: $some-color; }
```
I will try to get a build out this weekend.

**Comment by Fatal1stZ** [comment]
Thank you. Any news?
