### ISSUE TITLE
Publish 2.3.2 to npm

### ISSUE THREAD

**Issue by pfischer1290** [arnthor3/react-bootstrap-toggle#33]
please publish new version 2.3.2 to npm registry.

Thx

**Comment by arnthor3** [comment]
I will try to make it tonight if I find the time. Thanks for the pull request BTW, I am actually looking for someone to take this project over if you are interested, just throwing it out there.

**Comment by arnthor3** [comment]
published

**Comment by pfischer1290** [comment]
> I will try to make it tonight if I find the time. Thanks for the pull request BTW, I am actually looking for someone to take this project over if you are interested, just throwing it out there.

thx for your effort. 
id be happy to become a maintainer of this project if you are interested.

**Comment by arnthor3** [comment]
Ok, I made you a collaborator to begin with, I think it would be best either to create a new organisation or just transfer this to your account, what do you think? Also, I have never given up a name in npm before, I guess there is a tutorial somewhere for that :)

**Comment by arnthor3** [comment]
@pfischer1290 Do you have an npm account? What would be the best way to hand the project over?
