### ISSUE TITLE
Does not support FontAwesomeIcons in labels

### ISSUE THREAD

**Issue by nicoger** [arnthor3/react-bootstrap-toggle#34]
![image](https://user-images.githubusercontent.com/34345458/57836355-cdb30b00-77c0-11e9-94da-9b7c9f38e8f2.png)

This error is returned when a font awesome icon is placed in labels.
If it's <i></i> the error is thrown when you click on the button.
If it's <FontAwesomeIcon/> the error is thrown at page loading.

**Comment by pfischer1290** [comment]
Hi @nicoger,
can you provide your Code? Most likely your Implementation is not correct. 

If you insert Font-Awesome like that, its working for me:

´´´
import Toggle from 'react-bootstrap-toggle';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faExclamationTriangle } from '@fortawesome/free-solid-svg-icons';

<Toggle on={<FontAwesomeIcon icon={faExclamationTriangle} />} [...]/>
´´´
