### ISSUE TITLE
How to run unit tests using Mocha and Chai

### ISSUE THREAD

**Issue by Gothbag** [arnthor3/react-bootstrap-toggle#4]
Greetings,
When I try to unit test the component using Mocha and Chai I get a strange reference error "getComputedStyle is not defined". Is there a way to solve this?

Thank you very much

**Comment by arnthor3** [comment]
Hi,
You could try a Sinon stub. If you paste a code example I would be happy to look it over. Also if you would like to add tests to this project I would be happy to accept a pull request :)

**Comment by arnthor3** [comment]
I am closing you this, you are welcome to do a pull request if you want to try to add tests and do some refactoring on this.
