### ISSUE TITLE
PropTypes warnings

### ISSUE THREAD

**Issue by dule** [arnthor3/react-bootstrap-toggle#6]
I'm getting a series of React warnings from this library:
````
Warning: You are manually calling a React.PropTypes validation function for the `onstyle` prop on `ReactBootstrapToggle`. This is deprecated and will not work in production with the next major version. You may be seeing this warning due to a third-party PropTypes library. See https://fb.me/react-warning-dont-call-proptypes for details.
````
(One for each of the PropTypes defined in the lib)
I can't tell why though, it appears your use of `PropTypes` should still be valid..

**Comment by arnthor3** [comment]
I am going to try to reproduce it and see what I find.

**Comment by arnthor3** [comment]
I am trying to reproduce this but I  just cant seem to get that error. I looked over the [documents](https://facebook.github.io/react/warnings/dont-call-proptypes.html) and this looks to be all right in the code as you pointed out.

**Comment by arnthor3** [comment]
Could you confirm that you are getting those errors on 2.0.2? I would love to fix this as well.

**Comment by dule** [comment]
Yea, I'm still getting these on 2.0.2. I'm trying to narrow it down, and/or reproduce in an isolated project for you.

**Comment by dule** [comment]
I upgraded my react, and these warnings have seem to have gone away. So all good :).
