### ISSUE TITLE
Issue with onClick arguments

### ISSUE THREAD

**Issue by dule** [arnthor3/react-bootstrap-toggle#7]
Sorry, kicking the tires a bit today.

This line:
https://github.com/arnthor3/react-bootstrap-toggle/blob/3e42e9e781177e5ab23f0b4971c35a2a8ed47239/src/react-bootstrap-toggle.jsx#L28

Appears to call the callback with `!this.state.active`, unless I'm misinterpreting something, shouldn't it be calling the callback with `!this.props.active`?

**Comment by arnthor3** [comment]
No problem,

Yes I was moving the state out of the component, guess I missed that one :)
