### ISSUE TITLE
Impossibility of define an ID for React bootstrap toggle 

### ISSUE THREAD

**Issue by edigley** [arnthor3/react-bootstrap-toggle#8]
When trying to define an ID for the react bootstrap toggle (passing the usual id property for JSX tag), the rendered element doesn't have an id property. After inspecting the generated html element on the browser, we can see that the defined id is ignored. As this approach of defining a custom id for elements is very important for later identifying the element, I would like to know if it is in the roadmap of this project to support the receiving of the id.

**Comment by arnthor3** [comment]
Yes, of course. Do you want to do a pull request?

**Comment by arnthor3** [comment]
fixed in version 2.0.5
